"""ThrownAwayPost

Revision ID: 24c9822cbf38
Revises: ecb3fd1f0913
Create Date: 2018-08-19 02:09:31.164098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c9822cbf38'
down_revision = 'ecb3fd1f0913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thrown_away_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thrown_away_post_name'), 'thrown_away_post', ['name'], unique=True)
    op.create_index(op.f('ix_thrown_away_post_timestamp'), 'thrown_away_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thrown_away_post_timestamp'), table_name='thrown_away_post')
    op.drop_index(op.f('ix_thrown_away_post_name'), table_name='thrown_away_post')
    op.drop_table('thrown_away_post')
    # ### end Alembic commands ###
