"""Test catergory

Revision ID: 25d90c9d0624
Revises: c7e6e1dbcc27
Create Date: 2018-08-07 06:32:58.017731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d90c9d0624'
down_revision = 'c7e6e1dbcc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catergory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catergory_name'), 'catergory', ['name'], unique=True)
    op.add_column('post', sa.Column('cat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'catergory', ['cat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'cat_id')
    op.drop_index(op.f('ix_catergory_name'), table_name='catergory')
    op.drop_table('catergory')
    # ### end Alembic commands ###
