"""Add NewPost

Revision ID: cb7bd8a1fcdc
Revises: 24c9822cbf38
Create Date: 2018-08-19 02:42:53.152433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7bd8a1fcdc'
down_revision = '24c9822cbf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_post_name'), 'new_post', ['name'], unique=True)
    op.create_index(op.f('ix_new_post_timestamp'), 'new_post', ['timestamp'], unique=False)
    op.drop_index('ix_catergory2_name', table_name='catergory2')
    op.drop_table('catergory2')
    op.drop_index('ix_thrown_away_post_name', table_name='thrown_away_post')
    op.drop_index('ix_thrown_away_post_timestamp', table_name='thrown_away_post')
    op.drop_table('thrown_away_post')
    op.drop_column('post', 'cat_id2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cat_id2', sa.INTEGER(), nullable=True))
    op.create_table('thrown_away_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_thrown_away_post_timestamp', 'thrown_away_post', ['timestamp'], unique=False)
    op.create_index('ix_thrown_away_post_name', 'thrown_away_post', ['name'], unique=1)
    op.create_table('catergory2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catergory2_name', 'catergory2', ['name'], unique=1)
    op.drop_index(op.f('ix_new_post_timestamp'), table_name='new_post')
    op.drop_index(op.f('ix_new_post_name'), table_name='new_post')
    op.drop_table('new_post')
    # ### end Alembic commands ###
