"""empty message

Revision ID: ecb3fd1f0913
Revises: 163b91eed8df
Create Date: 2018-08-08 02:48:08.999087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb3fd1f0913'
down_revision = '163b91eed8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post2_timestamp', table_name='post2')
    op.drop_table('post2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('cat_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['catergory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post2_timestamp', 'post2', ['timestamp'], unique=False)
    # ### end Alembic commands ###
